### ISSUE TITLE
Event Type checking

### ISSUE THREAD

**Issue by ddavness** [ddavness/object-event#2]
In the future, we should be able to allow developers to enforce a specific type when declaring an event:

```ts
let event = new ObjectEvent<funcType>() // Is this valid?
```

So that functions being connected to said event must to take the argument types defined within the event:

```ts
let event = new ObjectEvent<(a: number, b: number) => void>()

// ERROR!
event.Connect(function(a: string) {
    print(a)
})
```

## So the tackling goes as following:

- Verify whether this is possible;
- Investigate the syntax for this;
- Implement!

**Comment by ddavness** [comment]
I think it might be possible. Opened a dev branch for this.

**Comment by ddavness** [comment]
We might be able to accomplish this by exposing two versions of the interface:

`ObjectEvent` - behavior will be the one we're used to (pass anything, receive any)

`ObjectEvent<T1, T2, T3, ...>` - this generic will restrict whatever you'll be able to pass in, and what kind of functions you can connect to (but we ensure type safety at compile time)

**Comment by tacheometry** [comment]
This would be hard to do without writing the entire module in TS.

**Comment by ddavness** [comment]
I'm not sure - I hadn't the time to check this one out so far, but we might be able to make it with Typescript 4 maybe?

**Comment by ddavness** [comment]
Not as "beautiful" as I wanted, but this does the trick
